server:
  port: 800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zizhihotel?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher



mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
pattern:
  name: 本地环境local

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  jackson:
#    data-format:yyyy-MM-dd HH:mm:ss
#    time-zone:GMT+8
